version: '3'

services:

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    expose:
      - 9000
    volumes:
      - ./web/:/var/www/html
      - ./dockerfiles/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - PakAG

  php:
    hostname: "foobar"
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    ports:
      - "9003:9003"
      - "25:25"
    volumes:
      - ./web/:/var/www/html
      - ./dockerfiles/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - ./dockerfiles/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./dockerfiles/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - PakAG

  mysql:
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - mysqlDB:/mysqlDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: root
    networks:
      - PakAG

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - PakAG

volumes:
  mysqlDB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Erronka/container/mysqlDB

networks:
  PakAG:
    driver: bridge